// Merge rules — deterministic, not left to the caller. MVP_PLAN_V3.md §12
// ("Ingestion Envelope" → "Merge rules") is the whole contract; see
// docs/decisions/0007-equal-occurredat-ties-break-on-eventid.md for the one gap the plan
// left open (the tie-break when two completion events share an identical `occurredAt`).
//
// Scope: this file is the pure merge-rule logic only — no HTTP, no persistence, no batch
// handling. It takes an entity's existing merge state (or `undefined` if the entity has
// never been seen) plus one incoming event, and returns the next merge state. Everything
// about *how* a raw wire event becomes a `MergeEvent` (parsing, schema validation, the
// server-generated `receivedAt`) belongs to the caller — `p2.ingest-endpoint`, not here.
//
// `MergeEvent.fields` is deliberately an opaque bag rather than the typed
// `RunStartedPayload` / `StepStartedPayload` / … shapes from `platform/shared/schema/**`.
// Those types are not importable from this lane: `@lengentic/shared` is not a declared
// dependency of `platform/api`, and adding it means editing `platform/api/package.json`,
// which sits outside this packet's `allowed_paths` (`platform/api/src/**`). The caller
// (which already depends on `@lengentic/shared` to validate the wire event) is
// responsible for narrowing `fields` back to a typed payload after merging.

/** Stored status. Never `STALE` — that is derived at read time (ADR/`platform/shared/README.md`). */
export type MergeEntityStatus = 'RUNNING' | 'COMPLETED' | 'FAILED';

/** The two terminal statuses a completion event may carry. */
export type MergeTerminalStatus = 'COMPLETED' | 'FAILED';

export type MergeEventKind = 'start' | 'completion';

/**
 * One already-validated telemetry event, reduced to what the merge rules need.
 *
 * `occurredAt` is the client clock (used for field precedence and the ADR 0007
 * tie-break). `receivedAt` is the server clock, epoch milliseconds, generated by the
 * caller at ingestion time — kept as an explicit input (not read from `Date.now()`
 * in here) so this module stays a pure function.
 */
export interface MergeEvent {
  readonly eventId: string;
  readonly entityId: string;
  readonly occurredAt: string;
  readonly receivedAt: number;
  readonly kind: MergeEventKind;
  /** Required when `kind === 'completion'`; absent for `'start'`. */
  readonly status?: MergeTerminalStatus;
  /** Start payload fields, or completion payload fields other than `status`. */
  readonly fields: Readonly<Record<string, unknown>>;
}

/** The merged state of one Run or Step, independent of which entity kind it is. */
export interface EntityMergeState {
  readonly entityId: string;
  readonly status: MergeEntityStatus;
  readonly startedAt: string | null;
  readonly startFields: Readonly<Record<string, unknown>> | null;
  readonly completedAt: string | null;
  readonly completionFields: Readonly<Record<string, unknown>> | null;
  /** The `eventId` that currently owns `completedAt`/`completionFields` — carried forward so a
   *  future tie (identical `occurredAt`) has something to compare against (ADR 0007). */
  readonly completionEventId: string | null;
  /** The `eventId` that currently owns `startedAt`/`startFields` — mirrors `completionEventId`
   *  so a future start-side tie (identical `occurredAt`) has something to compare against. */
  readonly startEventId: string | null;
  /** Server clock, epoch ms. Monotonic — never regresses, even if an older event is processed later. */
  readonly lastEventAt: number;
}

/**
 * Conflicting terminal states (MVP_PLAN_V3.md §12, OD-3): `FAILED` always wins over
 * `COMPLETED`, regardless of which one was observed first. "A failure that was observed
 * is more informative than a success that was also observed."
 *
 * This resolves `status` only. `completedAt` / other completion fields are resolved
 * independently by `mergeEvent`'s last-writer-wins-by-`occurredAt` rule — a later
 * `COMPLETED` event can still update `completedAt` even while `FAILED` keeps the status.
 */
export function resolveTerminalStatus(
  existing: MergeEntityStatus,
  incoming: MergeTerminalStatus,
): MergeTerminalStatus {
  if (existing === 'RUNNING') {
    return incoming;
  }
  if (existing === 'FAILED' || incoming === 'FAILED') {
    return 'FAILED';
  }
  return 'COMPLETED';
}

/**
 * Compares two `occurredAt` instants. Positive when `a` is later than `b`, negative when
 * earlier, zero when they name the same instant (regardless of how the offset is
 * spelled) — that zero is exactly the case ADR 0007 hands off to the `eventId` tie-break.
 */
function compareOccurredAt(a: string, b: string): number {
  return Date.parse(a) - Date.parse(b);
}

/**
 * Field precedence, completion side (MVP_PLAN_V3.md §12): last writer wins by
 * `occurredAt`, not arrival order. An identical `occurredAt` breaks on the
 * lexicographically greater `eventId` (docs/decisions/0007), never on arrival order.
 */
function shouldReplaceCompletion(
  current: EntityMergeState,
  event: MergeEvent & { readonly status: MergeTerminalStatus },
): boolean {
  if (current.completionEventId === null || current.completedAt === null) {
    return true;
  }
  const diff = compareOccurredAt(event.occurredAt, current.completedAt);
  if (diff !== 0) {
    return diff > 0;
  }
  return event.eventId > current.completionEventId;
}

/**
 * Field precedence, start side (MVP_PLAN_V3.md §12): "first writer wins" means first BY
 * `occurredAt` — the earliest-occurring start event keeps `startedAt`/`startFields`,
 * regardless of which one this process happened to see first. Arrival-order dependence was
 * considered and rejected (the same network-timing hazard `MVP_PLAN_V3.md:511-512` calls out
 * for the completion side; ADR 0007's Consequences require the merge to stay "a pure function
 * of the event set, independent of arrival order... replaying a batch cannot change an
 * answer" — that guarantee has to hold for both sides of the merge, not only completion).
 *
 * The tie-break mirrors ADR 0007 rather than reusing it: that ADR picks the
 * lexicographically GREATER `eventId` to stand in for "last" when two completions share an
 * instant. Here the earliest write wins, so the mirror image is required: on an exact
 * `occurredAt` tie, the lexicographically LESSER `eventId` stands in for "first".
 */
function shouldReplaceStart(current: EntityMergeState, event: MergeEvent): boolean {
  if (current.startEventId === null || current.startedAt === null) {
    return true;
  }
  const diff = compareOccurredAt(event.occurredAt, current.startedAt);
  if (diff !== 0) {
    return diff < 0;
  }
  return event.eventId < current.startEventId;
}

function emptyState(entityId: string): EntityMergeState {
  return {
    entityId,
    status: 'RUNNING',
    startedAt: null,
    startFields: null,
    completedAt: null,
    completionFields: null,
    completionEventId: null,
    startEventId: null,
    lastEventAt: -Infinity,
  };
}

/**
 * Applies one incoming event to an entity's existing merge state and returns the next
 * state. `current === undefined` means the entity has never been seen — the five rules
 * in MVP_PLAN_V3.md §12 all fall out of this single reducer:
 *
 * - Out-of-order start/completion: an unseen entity that first sees a completion event is
 *   created already terminal; a later start event only ever fills start fields.
 * - Field precedence: start fields are first-writer-wins BY `occurredAt` (earliest instant
 *   keeps them, never the arrival order this process happened to see them in); completion
 *   fields are last-writer-wins by `occurredAt`. Both sides tie-break on `eventId` when
 *   `occurredAt` is identical — completion picks the greater id, start the lesser, mirror
 *   images of the same rule (ADR 0007:48: "Arrival order is never consulted, for any field,
 *   at any time").
 * - Conflicting terminal states: delegated to `resolveTerminalStatus` — FAILED wins.
 * - Late events on a terminal run: never rejected, always update `lastEventAt`, and may
 *   enrich `completionFields` (a shallow merge — keys absent from the new event keep their
 *   prior value, matching keys are overwritten). `status` can never move back to RUNNING
 *   because no code path here ever assigns RUNNING except `emptyState` — the start branch
 *   below carries `status` forward from `base` unconditionally and never reassigns it, so a
 *   duplicate or late start event on an already-terminal entity cannot reopen it
 *   (MVP_PLAN_V3.md:514-516, the section's only MUST).
 * - Orphans: `parentStepId` (when present) travels inside `fields` untouched — this
 *   function never inspects it, never looks up a parent, never rejects a missing one.
 */
export function mergeEvent(
  current: EntityMergeState | undefined,
  event: MergeEvent,
): EntityMergeState {
  const base = current ?? emptyState(event.entityId);
  const lastEventAt = Math.max(base.lastEventAt, event.receivedAt);

  if (event.kind === 'start') {
    const replaceStart = shouldReplaceStart(base, event);
    // `status` is intentionally absent from this branch's own overrides — it flows through
    // only via `...base`, unchanged, on every path. A start event (duplicate, late, or a
    // genuinely earlier one that wins the tie-break below) can update startedAt/startFields
    // but must NEVER be able to move status back toward RUNNING on an already-terminal
    // entity. If a future edit adds a `status` override here, `merge-rules.spec.ts`'s reopen
    // guard test goes red.
    return {
      ...base,
      startedAt: replaceStart ? event.occurredAt : base.startedAt,
      // Shallow-copied so a caller mutating its own `event.fields` object after this call
      // returns can never retroactively change the state this function already returned —
      // this module stays a pure function of its inputs at the moment it was called.
      startFields: replaceStart ? { ...event.fields } : base.startFields,
      startEventId: replaceStart ? event.eventId : base.startEventId,
      lastEventAt,
    };
  }

  // kind === 'completion'
  if (event.status === undefined) {
    throw new Error(
      `mergeEvent: a completion event must carry a status (eventId=${event.eventId}, entityId=${event.entityId})`,
    );
  }
  const completionEvent = event as MergeEvent & { readonly status: MergeTerminalStatus };

  const status = resolveTerminalStatus(base.status, completionEvent.status);
  const replaceCompletion = shouldReplaceCompletion(base, completionEvent);

  return {
    ...base,
    status,
    completedAt: replaceCompletion ? completionEvent.occurredAt : base.completedAt,
    // Shallow MERGE, not replace: MVP_PLAN_V3.md:514-515 says a late event on a terminal run
    // "may enrich the run" — plain reading is additive. Keys in the new event overwrite
    // matching keys from before (still last-writer-wins per field); keys the new event does
    // not carry are preserved rather than silently dropped. `{ ...base.completionFields,
    // ...completionEvent.fields }` also produces a fresh object either way, which is what
    // keeps this side immune to the same caller-mutates-its-event aliasing hazard as start.
    completionFields: replaceCompletion
      ? { ...base.completionFields, ...completionEvent.fields }
      : base.completionFields,
    completionEventId: replaceCompletion ? completionEvent.eventId : base.completionEventId,
    lastEventAt,
  };
}
