// Merge rules — deterministic, not left to the caller. MVP_PLAN_V3.md §12
// ("Ingestion Envelope" → "Merge rules") is the whole contract; see
// docs/decisions/0007-equal-occurredat-ties-break-on-eventid.md for the one gap the plan
// left open (the tie-break when two completion events share an identical `occurredAt`).
//
// Scope: this file is the pure merge-rule logic only — no HTTP, no persistence, no batch
// handling. It takes an entity's existing merge state (or `undefined` if the entity has
// never been seen) plus one incoming event, and returns the next merge state. Everything
// about *how* a raw wire event becomes a `MergeEvent` (parsing, schema validation, the
// server-generated `receivedAt`) belongs to the caller — `p2.ingest-endpoint`, not here.
//
// `MergeEvent.fields` is deliberately an opaque bag rather than the typed
// `RunStartedPayload` / `StepStartedPayload` / … shapes from `platform/shared/schema/**`.
// Those types are not importable from this lane: `@lengentic/shared` is not a declared
// dependency of `platform/api`, and adding it means editing `platform/api/package.json`,
// which sits outside this packet's `allowed_paths` (`platform/api/src/**`). The caller
// (which already depends on `@lengentic/shared` to validate the wire event) is
// responsible for narrowing `fields` back to a typed payload after merging.

/** Stored status. Never `STALE` — that is derived at read time (ADR/`platform/shared/README.md`). */
export type MergeEntityStatus = 'RUNNING' | 'COMPLETED' | 'FAILED';

/** The two terminal statuses a completion event may carry. */
export type MergeTerminalStatus = 'COMPLETED' | 'FAILED';

export type MergeEventKind = 'start' | 'completion';

/**
 * One already-validated telemetry event, reduced to what the merge rules need.
 *
 * `occurredAt` is the client clock (used for field precedence and the ADR 0007
 * tie-break). `receivedAt` is the server clock, epoch milliseconds, generated by the
 * caller at ingestion time — kept as an explicit input (not read from `Date.now()`
 * in here) so this module stays a pure function.
 */
export interface MergeEvent {
  readonly eventId: string;
  readonly entityId: string;
  readonly occurredAt: string;
  readonly receivedAt: number;
  readonly kind: MergeEventKind;
  /** Required when `kind === 'completion'`; absent for `'start'`. */
  readonly status?: MergeTerminalStatus;
  /** Start payload fields, or completion payload fields other than `status`. */
  readonly fields: Readonly<Record<string, unknown>>;
}

/** The merged state of one Run or Step, independent of which entity kind it is. */
export interface EntityMergeState {
  readonly entityId: string;
  readonly status: MergeEntityStatus;
  readonly startedAt: string | null;
  readonly startFields: Readonly<Record<string, unknown>> | null;
  readonly completedAt: string | null;
  readonly completionFields: Readonly<Record<string, unknown>> | null;
  /** The `eventId` that currently owns `completedAt`/`completionFields` — carried forward so a
   *  future tie (identical `occurredAt`) has something to compare against (ADR 0007). */
  readonly completionEventId: string | null;
  /** Server clock, epoch ms. Monotonic — never regresses, even if an older event is processed later. */
  readonly lastEventAt: number;
}

/**
 * Conflicting terminal states (MVP_PLAN_V3.md §12, OD-3): `FAILED` always wins over
 * `COMPLETED`, regardless of which one was observed first. "A failure that was observed
 * is more informative than a success that was also observed."
 *
 * This resolves `status` only. `completedAt` / other completion fields are resolved
 * independently by `mergeEvent`'s last-writer-wins-by-`occurredAt` rule — a later
 * `COMPLETED` event can still update `completedAt` even while `FAILED` keeps the status.
 */
export function resolveTerminalStatus(
  existing: MergeEntityStatus,
  incoming: MergeTerminalStatus,
): MergeTerminalStatus {
  if (existing === 'RUNNING') {
    return incoming;
  }
  if (existing === 'FAILED' || incoming === 'FAILED') {
    return 'FAILED';
  }
  return 'COMPLETED';
}

/**
 * Compares two `occurredAt` instants. Positive when `a` is later than `b`, negative when
 * earlier, zero when they name the same instant (regardless of how the offset is
 * spelled) — that zero is exactly the case ADR 0007 hands off to the `eventId` tie-break.
 */
function compareOccurredAt(a: string, b: string): number {
  return Date.parse(a) - Date.parse(b);
}

/**
 * Field precedence, completion side (MVP_PLAN_V3.md §12): last writer wins by
 * `occurredAt`, not arrival order. An identical `occurredAt` breaks on the
 * lexicographically greater `eventId` (docs/decisions/0007), never on arrival order.
 */
function shouldReplaceCompletion(
  current: EntityMergeState,
  event: MergeEvent & { readonly status: MergeTerminalStatus },
): boolean {
  if (current.completionEventId === null || current.completedAt === null) {
    return true;
  }
  const diff = compareOccurredAt(event.occurredAt, current.completedAt);
  if (diff !== 0) {
    return diff > 0;
  }
  return event.eventId > current.completionEventId;
}

function emptyState(entityId: string): EntityMergeState {
  return {
    entityId,
    status: 'RUNNING',
    startedAt: null,
    startFields: null,
    completedAt: null,
    completionFields: null,
    completionEventId: null,
    lastEventAt: -Infinity,
  };
}

/**
 * Applies one incoming event to an entity's existing merge state and returns the next
 * state. `current === undefined` means the entity has never been seen — the five rules
 * in MVP_PLAN_V3.md §12 all fall out of this single reducer:
 *
 * - Out-of-order start/completion: an unseen entity that first sees a completion event is
 *   created already terminal; a later start event only ever fills start fields.
 * - Field precedence: start fields are first-writer-wins (by processing order); completion
 *   fields are last-writer-wins by `occurredAt`, tie-broken by `eventId` (ADR 0007).
 * - Conflicting terminal states: delegated to `resolveTerminalStatus` — FAILED wins.
 * - Late events on a terminal run: never rejected, always update `lastEventAt`, and can
 *   still enrich `completedAt`/`completionFields`; `status` can never move back to RUNNING
 *   because no code path here ever assigns RUNNING except `emptyState`.
 * - Orphans: `parentStepId` (when present) travels inside `fields` untouched — this
 *   function never inspects it, never looks up a parent, never rejects a missing one.
 */
export function mergeEvent(
  current: EntityMergeState | undefined,
  event: MergeEvent,
): EntityMergeState {
  const base = current ?? emptyState(event.entityId);
  const lastEventAt = Math.max(base.lastEventAt, event.receivedAt);

  if (event.kind === 'start') {
    if (base.startFields !== null) {
      // First writer already won. A second start event is accepted (it is not an
      // error — retries and duplicate starts happen) but changes nothing except that
      // the entity has now been touched more recently.
      return { ...base, lastEventAt };
    }
    return {
      ...base,
      startedAt: event.occurredAt,
      startFields: event.fields,
      lastEventAt,
    };
  }

  // kind === 'completion'
  if (event.status === undefined) {
    throw new Error(
      `mergeEvent: a completion event must carry a status (eventId=${event.eventId}, entityId=${event.entityId})`,
    );
  }
  const completionEvent = event as MergeEvent & { readonly status: MergeTerminalStatus };

  const status = resolveTerminalStatus(base.status, completionEvent.status);
  const replaceCompletion = shouldReplaceCompletion(base, completionEvent);

  return {
    ...base,
    status,
    completedAt: replaceCompletion ? completionEvent.occurredAt : base.completedAt,
    completionFields: replaceCompletion ? completionEvent.fields : base.completionFields,
    completionEventId: replaceCompletion ? completionEvent.eventId : base.completionEventId,
    lastEventAt,
  };
}
