// Merge rules — deterministic, not left to the caller. MVP_PLAN_V3.md §12
// ("Ingestion Envelope" → "Merge rules") is the whole contract; see
// docs/decisions/0007-equal-occurredat-ties-break-on-eventid.md for the one gap the plan
// left open (the tie-break when two completion events share an identical `occurredAt`).
//
// Scope: this file is the pure merge-rule logic only — no HTTP, no persistence, no batch
// handling. It takes an entity's existing merge state (or `undefined` if the entity has
// never been seen) plus one incoming event, and returns the next merge state. Everything
// about *how* a raw wire event becomes a `MergeEvent` (parsing, schema validation, the
// server-generated `receivedAt`) belongs to the caller — `p2.ingest-endpoint`, not here.
//
// `MergeEvent.fields` is deliberately an opaque bag rather than the typed
// `RunStartedPayload` / `StepStartedPayload` / … shapes from `platform/shared/schema/**`.
// Those types are not importable from this lane: `@lengentic/shared` is not a declared
// dependency of `platform/api`, and adding it means editing `platform/api/package.json`,
// which sits outside this packet's `allowed_paths` (`platform/api/src/**`). The caller
// (which already depends on `@lengentic/shared` to validate the wire event) is
// responsible for narrowing `fields` back to a typed payload after merging.
//
// Purity: a caller mutating its own event object — at any depth, not only its top-level
// keys — after calling `mergeEvent` cannot change state this function already returned.
// Both `startFields` and `completionFields` are populated via `structuredClone`, not a
// shallow spread, at the point each event's fields are read in.

/** Stored status. Never `STALE` — that is derived at read time (ADR/`platform/shared/README.md`). */
export type MergeEntityStatus = 'RUNNING' | 'COMPLETED' | 'FAILED';

/** The two terminal statuses a completion event may carry. */
export type MergeTerminalStatus = 'COMPLETED' | 'FAILED';

export type MergeEventKind = 'start' | 'completion';

/**
 * One already-validated telemetry event, reduced to what the merge rules need.
 *
 * `occurredAt` is the client clock (used for field precedence and the ADR 0007
 * tie-break). `receivedAt` is the server clock, epoch milliseconds, generated by the
 * caller at ingestion time — kept as an explicit input (not read from `Date.now()`
 * in here) so this module stays a pure function.
 */
export interface MergeEvent {
  readonly eventId: string;
  readonly entityId: string;
  readonly occurredAt: string;
  readonly receivedAt: number;
  readonly kind: MergeEventKind;
  /** Required when `kind === 'completion'`; absent for `'start'`. */
  readonly status?: MergeTerminalStatus;
  /** Start payload fields, or completion payload fields other than `status`. */
  readonly fields: Readonly<Record<string, unknown>>;
}

/** Which completion event last wrote one `completionFields` key. ADR 0007's order key,
 *  recorded per key rather than per event. Internal bookkeeping — not a wire value. */
export interface CompletionFieldOrigin {
  readonly occurredAt: string;
  readonly eventId: string;
}

/** The merged state of one Run or Step, independent of which entity kind it is. */
export interface EntityMergeState {
  readonly entityId: string;
  readonly status: MergeEntityStatus;
  readonly startedAt: string | null;
  readonly startFields: Readonly<Record<string, unknown>> | null;
  readonly completedAt: string | null;
  readonly completionFields: Readonly<Record<string, unknown>> | null;
  /** The `eventId` that currently owns `completedAt`/`completionFields` — carried forward so a
   *  future tie (identical `occurredAt`) has something to compare against (ADR 0007). */
  readonly completionEventId: string | null;
  /** The `eventId` that currently owns `startedAt`/`startFields` — mirrors `completionEventId`
   *  so a future start-side tie (identical `occurredAt`) has something to compare against. */
  readonly startEventId: string | null;
  /** Per-key provenance for `completionFields`. Always an object; `{}` before any completion
   *  event. Never null — `completionFields === null` already carries "never completed". */
  readonly completionFieldOrigins: Readonly<Record<string, CompletionFieldOrigin>>;
  /** Server clock, epoch ms. Monotonic — never regresses, even if an older event is processed later. */
  readonly lastEventAt: number;
}

/**
 * Conflicting terminal states (MVP_PLAN_V3.md §12, OD-3): `FAILED` always wins over
 * `COMPLETED`, regardless of which one was observed first. "A failure that was observed
 * is more informative than a success that was also observed."
 *
 * This resolves `status` only. `completedAt` / other completion fields are resolved
 * independently by `mergeEvent`'s last-writer-wins-by-`occurredAt` rule — a later
 * `COMPLETED` event can still update `completedAt` even while `FAILED` keeps the status.
 */
export function resolveTerminalStatus(
  existing: MergeEntityStatus,
  incoming: MergeTerminalStatus,
): MergeTerminalStatus {
  if (existing === 'RUNNING') {
    return incoming;
  }
  if (existing === 'FAILED' || incoming === 'FAILED') {
    return 'FAILED';
  }
  return 'COMPLETED';
}

/**
 * Compares two `occurredAt` instants. Positive when `a` is later than `b`, negative when
 * earlier, zero when they name the same instant (regardless of how the offset is
 * spelled) — that zero is exactly the case ADR 0007 hands off to the `eventId` tie-break.
 */
function compareOccurredAt(a: string, b: string): number {
  return Date.parse(a) - Date.parse(b);
}

/**
 * Total order over completion events (ADR 0007 §3): later `occurredAt` wins; an identical
 * `occurredAt` breaks on the lexicographically greater `eventId`. Never arrival order.
 * Shared by `shouldReplaceCompletion` (the `status`/`completedAt`/`completionEventId`
 * winner) and the per-key `completionFields` fold in `mergeEvent`, so the two cannot drift
 * apart into disagreeing about which event is "later".
 */
function compareCompletionOrder(a: CompletionFieldOrigin, b: CompletionFieldOrigin): number {
  const diff = compareOccurredAt(a.occurredAt, b.occurredAt);
  if (diff !== 0) return diff;
  return a.eventId < b.eventId ? -1 : a.eventId > b.eventId ? 1 : 0;
}

/**
 * Field precedence, completion side (MVP_PLAN_V3.md §12): last writer wins by
 * `occurredAt`, not arrival order. An identical `occurredAt` breaks on the
 * lexicographically greater `eventId` (docs/decisions/0007), never on arrival order.
 */
function shouldReplaceCompletion(
  current: EntityMergeState,
  event: MergeEvent & { readonly status: MergeTerminalStatus },
): boolean {
  if (current.completionEventId === null || current.completedAt === null) {
    return true;
  }
  return (
    compareCompletionOrder(
      { occurredAt: event.occurredAt, eventId: event.eventId },
      { occurredAt: current.completedAt, eventId: current.completionEventId },
    ) > 0
  );
}

/**
 * Field precedence, start side (MVP_PLAN_V3.md §12): "first writer wins" means first BY
 * `occurredAt` — the earliest-occurring start event keeps `startedAt`/`startFields`,
 * regardless of which one this process happened to see first. Arrival-order dependence was
 * considered and rejected (the same network-timing hazard `MVP_PLAN_V3.md:511-512` calls out
 * for the completion side; ADR 0007's Consequences require the merge to stay "a pure function
 * of the event set, independent of arrival order... replaying a batch cannot change an
 * answer" — that guarantee has to hold for both sides of the merge, not only completion).
 *
 * The tie-break mirrors ADR 0007 rather than reusing it: that ADR picks the
 * lexicographically GREATER `eventId` to stand in for "last" when two completions share an
 * instant. Here the earliest write wins, so the mirror image is required: on an exact
 * `occurredAt` tie, the lexicographically LESSER `eventId` stands in for "first".
 */
function shouldReplaceStart(current: EntityMergeState, event: MergeEvent): boolean {
  if (current.startEventId === null || current.startedAt === null) {
    return true;
  }
  const diff = compareOccurredAt(event.occurredAt, current.startedAt);
  if (diff !== 0) {
    return diff < 0;
  }
  return event.eventId < current.startEventId;
}

function emptyState(entityId: string): EntityMergeState {
  return {
    entityId,
    status: 'RUNNING',
    startedAt: null,
    startFields: null,
    completedAt: null,
    completionFields: null,
    completionEventId: null,
    startEventId: null,
    completionFieldOrigins: {},
    lastEventAt: -Infinity,
  };
}

/**
 * Applies one incoming event to an entity's existing merge state and returns the next
 * state. `current === undefined` means the entity has never been seen — the five rules
 * in MVP_PLAN_V3.md §12 all fall out of this single reducer:
 *
 * - Out-of-order start/completion: an unseen entity that first sees a completion event is
 *   created already terminal; a later start event only ever fills start fields.
 * - Field precedence: start fields are first-writer-wins BY `occurredAt` (earliest instant
 *   keeps them, never the arrival order this process happened to see them in); completion
 *   fields are last-writer-wins by `occurredAt`. Both sides tie-break on `eventId` when
 *   `occurredAt` is identical — completion picks the greater id, start the lesser, mirror
 *   images of the same rule (ADR 0007:48: "Arrival order is never consulted, for any field,
 *   at any time").
 * - Conflicting terminal states: delegated to `resolveTerminalStatus` — FAILED wins.
 * - Late events on a terminal run: never rejected, always update `lastEventAt`, and may
 *   enrich `completionFields`. Each key of `completionFields` is resolved independently
 *   against the total order in `compareCompletionOrder` (ADR 0007 §3: "arrival order is
 *   never consulted, for any field, at any time") — a key keeps whichever completion event
 *   wrote it last BY THAT ORDER, not by which event this process happened to see last, and
 *   `completionFieldOrigins` records that per-key winner so a still-later event can be
 *   compared against it. Keys absent from the incoming event keep their prior value; keys
 *   present are only overwritten when the incoming event outranks the key's current origin.
 *   `status` can never move back to RUNNING
 *   because no code path here ever assigns RUNNING except `emptyState` — the start branch
 *   below carries `status` forward from `base` unconditionally and never reassigns it, so a
 *   duplicate or late start event on an already-terminal entity cannot reopen it
 *   (MVP_PLAN_V3.md:514-516, the section's only MUST).
 * - Orphans: `parentStepId` (when present) travels inside `fields` untouched — this
 *   function never inspects it, never looks up a parent, never rejects a missing one.
 */
export function mergeEvent(
  current: EntityMergeState | undefined,
  event: MergeEvent,
): EntityMergeState {
  const base = current ?? emptyState(event.entityId);
  const lastEventAt = Math.max(base.lastEventAt, event.receivedAt);

  if (event.kind === 'start') {
    const replaceStart = shouldReplaceStart(base, event);
    // `status` is intentionally absent from this branch's own overrides — it flows through
    // only via `...base`, unchanged, on every path. A start event (duplicate, late, or a
    // genuinely earlier one that wins the tie-break below) can update startedAt/startFields
    // but must NEVER be able to move status back toward RUNNING on an already-terminal
    // entity. If a future edit adds a `status` override here, `merge-rules.spec.ts`'s reopen
    // guard test goes red.
    //
    // `startFields` is a WHOLESALE REPLACE by the winning event's own fields — never merged
    // with whatever `base.startFields` happened to hold already. That residue-merge design
    // (a prior attempt: "presence-based merge onto base.startFields", meant to stop a
    // metadata-less winner from blanking a prior winner's metadata) was reverted by fresh
    // independent verification (tester finding D3, 2026-08-20): merging onto
    // `base.startFields` makes the result depend on which OTHER start events this process
    // happened to fold in before the eventual winner arrived — exactly the arrival-order
    // dependence ADR 0007's Consequences forbid ("a pure function of the event set...
    // replaying a batch cannot change an answer" — for both sides of the merge, not only
    // completion). Proof: the same event set, submitted in different orders or split across
    // different request boundaries, persisted two different `metadata` values under the
    // presence-merge design (`.artifacts/evidence/2/tester-reverify/raw/order.json`,
    // `bonus.mjs`).
    //
    // Wholesale replace restores order-independence CHEAPLY: the winner itself is already a
    // pure function of the event set (`shouldReplaceStart`'s total order — earliest
    // `occurredAt`, tie-break the lesser `eventId` — is a min-reduction, associative and
    // commutative regardless of processing order). Once the winner is fixed, its own
    // `fields` is the ONLY input to `startFields` — nothing carried over from any other
    // event, winning or losing, so there is nothing left for arrival order to disturb.
    //
    // Known, accepted trade-off (documented, not silently different from what §12 promises):
    // a key ONLY ever supplied by a start event that is not the overall winner (whether it
    // lost outright or won an earlier round before a still-earlier event displaced it) is
    // never captured, even if the eventual winner never speaks to that key either — the same
    // "lossy but deterministic" shape the pre-presence-merge implementation had. Recovering
    // the lost keys would need per-key first-writer-wins provenance — the mirror of
    // `completionFieldOrigins` — persisted so it survives a reload between requests. Run/Step
    // have no such column (only `startEventId`, one winner for the whole entity) and adding
    // one is a schema.prisma change, out of this module's reach (`platform/api/src/**`, this
    // lane's `allowed_paths`). `merge-rules.spec.ts` proves the CURRENT contract instead: the
    // same event set produces an identical `startFields` across every permutation tried.
    const startFields = replaceStart ? structuredClone({ ...event.fields }) : base.startFields;
    return {
      ...base,
      startedAt: replaceStart ? event.occurredAt : base.startedAt,
      startFields,
      startEventId: replaceStart ? event.eventId : base.startEventId,
      lastEventAt,
    };
  }

  // kind === 'completion'
  if (event.status === undefined) {
    throw new Error(
      `mergeEvent: a completion event must carry a status (eventId=${event.eventId}, entityId=${event.entityId})`,
    );
  }
  const completionEvent = event as MergeEvent & { readonly status: MergeTerminalStatus };

  const status = resolveTerminalStatus(base.status, completionEvent.status);
  const replaceCompletion = shouldReplaceCompletion(base, completionEvent);

  // Per-key MERGE over the total order (ADR 0007 §3), not a shallow accumulate and not
  // gated on `replaceCompletion` — that flag governs only the separate `status` /
  // `completedAt` / `completionEventId` winner rule above. Each key of `completionFields`
  // keeps whichever completion event wrote it last BY `compareCompletionOrder`, tracked in
  // `completionFieldOrigins`, so the outcome cannot depend on which event this process
  // happened to process first (MVP_PLAN_V3.md:514-515's "may enrich" is additive, and
  // ADR 0007 §3 extends that "last writer" rule to per-key rather than per-event). Deep
  // clone at intake for the same aliasing-purity reason as the start branch.
  const clonedFields: Record<string, unknown> = structuredClone({ ...completionEvent.fields });
  const nextFields: Record<string, unknown> = { ...(base.completionFields ?? {}) };
  const nextOrigins: Record<string, CompletionFieldOrigin> = { ...base.completionFieldOrigins };
  const incoming: CompletionFieldOrigin = {
    occurredAt: completionEvent.occurredAt,
    eventId: completionEvent.eventId,
  };
  for (const [key, value] of Object.entries(clonedFields)) {
    const origin = nextOrigins[key];
    if (origin === undefined || compareCompletionOrder(incoming, origin) > 0) {
      nextFields[key] = value;
      nextOrigins[key] = incoming;
    }
  }

  return {
    ...base,
    status,
    completedAt: replaceCompletion ? completionEvent.occurredAt : base.completedAt,
    completionFields: nextFields,
    completionFieldOrigins: nextOrigins,
    completionEventId: replaceCompletion ? completionEvent.eventId : base.completionEventId,
    lastEventAt,
  };
}
